// Define user roles
import {USER_TYPE} from "../constants/userConstants"

// Define role-based redirect paths
export const DEFAULT_PATHS: Record<USER_TYPE, string> = {
  [USER_TYPE.CLIENT]: "/visaistic/application-tracker",
  [USER_TYPE.MANAGER]: "/visaistic/application-tracker",
  [USER_TYPE.ADMIN]: "/visaistic/manage-users",
};

// Define routes that are accessible to each role
export const ROLE_ROUTES: Record<USER_TYPE, string[]> = {
  [USER_TYPE.CLIENT]: ["/application-tracker", "/check-list", "/services", "/manage-users", "/manage-clients", "/checklist-details"],
  [USER_TYPE.MANAGER]: ["/application-tracker", "/check-list", "/services", "/manage-users", "/manage-clients", "/checklist-details"],
  [USER_TYPE.ADMIN]: ["/application-tracker", "/check-list", "/services", "/manage-users", "/manage-clients", "/checklist-details"],
};

// Define the navigation items for each role
export const roleBasedNavItems = {
  [USER_TYPE.CLIENT]: [
    { label: "Application Tracker", path: "/application-tracker" },
    { label: "Check list", path: "/check-list" },
  ],
  [USER_TYPE.MANAGER]: [
    { label: "Application Tracker", path: "/application-tracker" },
    { label: "Manage Users", path: "/manage-users" },
    { label: "Check list", path: "/check-list" },
    { label: "Services", path: "/services" },
    { label: "Manage Clients", path: "/manage-clients" },
  ],
  [USER_TYPE.ADMIN]: [
    { label: "Application Tracker", path: "/application-tracker" },
    { label: "Manage Users", path: "/manage-users" },
    { label: "Check list", path: "/check-list" },
    { label: "Services", path: "/services" },
    { label: "Manage Clients", path: "/manage-clients" },
  ],
};

// Define the default landing page for each role
export const defaultRoutes: Record<USER_TYPE, string> = {
  [USER_TYPE.CLIENT]: "/visaistic/application-tracker",
  [USER_TYPE.MANAGER]: "/visaistic/application-tracker",
  [USER_TYPE.ADMIN]: "/visaistic/manage-users",
};

export const SIGN_IN_STATUS_TYPE: Record<string, number> = {
  SUCCESS: 1,
  INCORRECT_PASSWORD: 2,
  EXPIRED_REQUEST_NOT_INITIATED: 3,
  EXPIRED_REQUEST_INITIATED: 4,
  INACTIVE_BY_ADMIN: 5,
  EMAIL_NOT_FOUND: 6,
};

export const SIGN_IN_STATUS_MESSAGE: Record<number, string> = {
  [SIGN_IN_STATUS_TYPE.SUCCESS]: "",
  [SIGN_IN_STATUS_TYPE.INCORRECT_PASSWORD]: "Incorrect password please try again.",
  [SIGN_IN_STATUS_TYPE.EXPIRED_REQUEST_NOT_INITIATED]:
    "Your password has expired. Request a new password to continue.",
  [SIGN_IN_STATUS_TYPE.EXPIRED_REQUEST_INITIATED]:
    "Your password reset request has been sent successfully.",
  [SIGN_IN_STATUS_TYPE.INACTIVE_BY_ADMIN]:
    "Your password has expired. Request a new password to continue.",
  [SIGN_IN_STATUS_TYPE.EMAIL_NOT_FOUND]: "Email does not exist.",
};

export const APPLICATION_STATUS: Record<string, number> = {
  STEP1_DONE: 1,
  STEP2_DONE: 2,
  STEP3_DONE: 3,
  STEP4_DONE: 4,
}

export enum EMAIL_TYPE {
  WELCOME = 1,
  PASSWORD_RESET = 2,
  APPLICATION_STATUS = 3,
  CREDENTIALS = 4,
  DOCUMENT_CHECKLIST = 5
}

// Enum for Queues
export enum APPLICATION_QUEUES {
  IN_TRANSIT = 1,
  SUBMISSION = 2,
  COLLECTION = 3,
  BILLING = 4,
}

// Enum for Statuses
export enum APPLICATION_EXTERNAL_STATUS {
  DOC_RECIVED = 1, // spelling requested by client
  DOC_AWAITED = 2,
  PASSPORT_AWAITED = 3,
  IN_TRANSIT = 4,
  PENDING_ADDITIONAL_DOCS = 5,
  PENDING_OTHERS = 6,
  PENDING_PERSONAL_APPEARANCE_SUBMISSION = 7,
  SUBMISSION_BY_APPOINTMENT = 8,
  SUBMISSION_PENDING_ADVANCE_PAYMENT = 9,

  OUT_FOR_SUBMISSION = 10,
  SUBMITTED = 11,
  UNDER_PROCESS = 12,
  RE_SUBMITTED = 13,
  APPROVAL_AWAITED = 14,
  PENDING_ADDITIONAL_DOCS_2 = 15,
  PENDING_CHECKLIST_ISSUED = 16,
  PENDING_DOCS_REFERRED = 17,
  PENDING_INTERNAL_VERIFICATION = 18,
  PENDING_MEDICAL_CLEARANCE = 19,
  PENDING_OTHERS_2 = 20,
  PENDING_PERSONAL_APPEARANCE_INTERVIEW = 21,
  PENDING_UNDER_PROCESS = 22,
  DOCS_RECEIVED = 23,
  PASSPORT_DISPATCHED_APPROVAL_AWAITED = 24,
  MRV_OBTAINED = 25,
  MRV_OBTAINED_APPOINTMENT_TAKEN = 26,

  VISA_REJECTED = 27,
  VISA_OBTAINED = 28,
  OBTAINED = 29,
  COLLECTED = 30,
  VISA_GRANTED_SENT = 31,
  VISA_REJECTED_SENT = 32,
  SENT = 33,
  SENT_BACK_WITHOUT_VISA = 34,
  WITHDRAWN_SENT = 35,
}

// Status to Queue Mapping
export const STATUS_TO_QUEUE: Record<APPLICATION_EXTERNAL_STATUS, APPLICATION_QUEUES> = {
  [APPLICATION_EXTERNAL_STATUS.DOC_RECIVED]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.DOC_AWAITED]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.PASSPORT_AWAITED]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.IN_TRANSIT]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.PENDING_ADDITIONAL_DOCS]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.PENDING_OTHERS]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.PENDING_PERSONAL_APPEARANCE_SUBMISSION]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.SUBMISSION_BY_APPOINTMENT]: APPLICATION_QUEUES.IN_TRANSIT,
  [APPLICATION_EXTERNAL_STATUS.SUBMISSION_PENDING_ADVANCE_PAYMENT]: APPLICATION_QUEUES.IN_TRANSIT,

  [APPLICATION_EXTERNAL_STATUS.OUT_FOR_SUBMISSION]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.SUBMITTED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.UNDER_PROCESS]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.RE_SUBMITTED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.APPROVAL_AWAITED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_ADDITIONAL_DOCS_2]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_CHECKLIST_ISSUED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_DOCS_REFERRED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_INTERNAL_VERIFICATION]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_MEDICAL_CLEARANCE]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_OTHERS_2]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_PERSONAL_APPEARANCE_INTERVIEW]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PENDING_UNDER_PROCESS]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.DOCS_RECEIVED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.PASSPORT_DISPATCHED_APPROVAL_AWAITED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.MRV_OBTAINED]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.MRV_OBTAINED_APPOINTMENT_TAKEN]: APPLICATION_QUEUES.SUBMISSION,
  [APPLICATION_EXTERNAL_STATUS.VISA_REJECTED]: APPLICATION_QUEUES.COLLECTION,
  [APPLICATION_EXTERNAL_STATUS.VISA_OBTAINED]: APPLICATION_QUEUES.COLLECTION,
  [APPLICATION_EXTERNAL_STATUS.OBTAINED]: APPLICATION_QUEUES.COLLECTION,
  [APPLICATION_EXTERNAL_STATUS.COLLECTED]: APPLICATION_QUEUES.COLLECTION,
  [APPLICATION_EXTERNAL_STATUS.VISA_GRANTED_SENT]: APPLICATION_QUEUES.BILLING,
  [APPLICATION_EXTERNAL_STATUS.VISA_REJECTED_SENT]: APPLICATION_QUEUES.BILLING,
  [APPLICATION_EXTERNAL_STATUS.SENT]: APPLICATION_QUEUES.BILLING,
  [APPLICATION_EXTERNAL_STATUS.SENT_BACK_WITHOUT_VISA]: APPLICATION_QUEUES.BILLING,
  [APPLICATION_EXTERNAL_STATUS.WITHDRAWN_SENT]: APPLICATION_QUEUES.BILLING,
};

// Queue to Status Mapping
export const QUEUE_TO_STATUS: Record<APPLICATION_QUEUES, APPLICATION_EXTERNAL_STATUS[]> = {
  [APPLICATION_QUEUES.IN_TRANSIT]: [
    APPLICATION_EXTERNAL_STATUS.DOC_RECIVED,
    APPLICATION_EXTERNAL_STATUS.DOC_AWAITED,
    APPLICATION_EXTERNAL_STATUS.PASSPORT_AWAITED,
    APPLICATION_EXTERNAL_STATUS.IN_TRANSIT,
    APPLICATION_EXTERNAL_STATUS.PENDING_ADDITIONAL_DOCS,
    APPLICATION_EXTERNAL_STATUS.PENDING_OTHERS,
    APPLICATION_EXTERNAL_STATUS.PENDING_PERSONAL_APPEARANCE_SUBMISSION,
    APPLICATION_EXTERNAL_STATUS.SUBMISSION_BY_APPOINTMENT,
    APPLICATION_EXTERNAL_STATUS.SUBMISSION_PENDING_ADVANCE_PAYMENT,
  ],
  [APPLICATION_QUEUES.SUBMISSION]: [
    APPLICATION_EXTERNAL_STATUS.OUT_FOR_SUBMISSION,
    APPLICATION_EXTERNAL_STATUS.SUBMITTED,
    APPLICATION_EXTERNAL_STATUS.UNDER_PROCESS,
    APPLICATION_EXTERNAL_STATUS.RE_SUBMITTED,
    APPLICATION_EXTERNAL_STATUS.APPROVAL_AWAITED,
    APPLICATION_EXTERNAL_STATUS.PENDING_ADDITIONAL_DOCS,
    APPLICATION_EXTERNAL_STATUS.PENDING_CHECKLIST_ISSUED,
    APPLICATION_EXTERNAL_STATUS.PENDING_DOCS_REFERRED,
    APPLICATION_EXTERNAL_STATUS.PENDING_INTERNAL_VERIFICATION,
    APPLICATION_EXTERNAL_STATUS.PENDING_MEDICAL_CLEARANCE,
    APPLICATION_EXTERNAL_STATUS.PENDING_PERSONAL_APPEARANCE_INTERVIEW,
    APPLICATION_EXTERNAL_STATUS.DOCS_RECEIVED,
    APPLICATION_EXTERNAL_STATUS.PASSPORT_DISPATCHED_APPROVAL_AWAITED,
    APPLICATION_EXTERNAL_STATUS.MRV_OBTAINED,
    APPLICATION_EXTERNAL_STATUS.MRV_OBTAINED_APPOINTMENT_TAKEN,
  ],
  [APPLICATION_QUEUES.COLLECTION]: [
    APPLICATION_EXTERNAL_STATUS.VISA_REJECTED,
    APPLICATION_EXTERNAL_STATUS.VISA_OBTAINED,
    APPLICATION_EXTERNAL_STATUS.OBTAINED,
    APPLICATION_EXTERNAL_STATUS.COLLECTED,
  ],
  [APPLICATION_QUEUES.BILLING]: [
    APPLICATION_EXTERNAL_STATUS.VISA_GRANTED_SENT,
    APPLICATION_EXTERNAL_STATUS.VISA_REJECTED_SENT,
    APPLICATION_EXTERNAL_STATUS.SENT,
    APPLICATION_EXTERNAL_STATUS.SENT_BACK_WITHOUT_VISA,
    APPLICATION_EXTERNAL_STATUS.WITHDRAWN_SENT,
  ],
};

// Queue to Display String Mapping
export const QUEUE_DISPLAY_MAP: Record<APPLICATION_QUEUES, string> = {
  [APPLICATION_QUEUES.IN_TRANSIT]: "In-Transit",
  [APPLICATION_QUEUES.SUBMISSION]: "Submission",
  [APPLICATION_QUEUES.COLLECTION]: "Collection",
  [APPLICATION_QUEUES.BILLING]: "Billing",
};

// Status to Display String Mapping
export const STATUS_DISPLAY_MAP: Record<APPLICATION_EXTERNAL_STATUS, string> = {
  [APPLICATION_EXTERNAL_STATUS.DOC_RECIVED]: "Doc Recived",
  [APPLICATION_EXTERNAL_STATUS.DOC_AWAITED]: "Doc Awaited",
  [APPLICATION_EXTERNAL_STATUS.PASSPORT_AWAITED]: "Passport Awaited",
  [APPLICATION_EXTERNAL_STATUS.IN_TRANSIT]: "In Transit",
  [APPLICATION_EXTERNAL_STATUS.PENDING_ADDITIONAL_DOCS]: "Pending - Additional Docs Required",
  [APPLICATION_EXTERNAL_STATUS.PENDING_OTHERS]: "Pending - Others",
  [APPLICATION_EXTERNAL_STATUS.PENDING_PERSONAL_APPEARANCE_SUBMISSION]: "Pending - Personal Appearance for Submission",
  [APPLICATION_EXTERNAL_STATUS.SUBMISSION_BY_APPOINTMENT]: "Submission by Appointment",
  [APPLICATION_EXTERNAL_STATUS.SUBMISSION_PENDING_ADVANCE_PAYMENT]: "Submission Pending Waiting for Advance Payment",

  [APPLICATION_EXTERNAL_STATUS.OUT_FOR_SUBMISSION]: "Out for Submission",
  [APPLICATION_EXTERNAL_STATUS.SUBMITTED]: "Submitted",
  [APPLICATION_EXTERNAL_STATUS.UNDER_PROCESS]: "Under Process",
  [APPLICATION_EXTERNAL_STATUS.RE_SUBMITTED]: "Re-submitted",
  [APPLICATION_EXTERNAL_STATUS.APPROVAL_AWAITED]: "Approval Awaited",
  [APPLICATION_EXTERNAL_STATUS.PENDING_ADDITIONAL_DOCS_2]: "Pending - Additional Docs Required",
  [APPLICATION_EXTERNAL_STATUS.PENDING_CHECKLIST_ISSUED]: "Pending - Checklist Issued",
  [APPLICATION_EXTERNAL_STATUS.PENDING_DOCS_REFERRED]: "Pending - Docs Referred",
  [APPLICATION_EXTERNAL_STATUS.PENDING_INTERNAL_VERIFICATION]: "Pending - Internal Verification",
  [APPLICATION_EXTERNAL_STATUS.PENDING_MEDICAL_CLEARANCE]: "Pending - Medical Clearance",
  [APPLICATION_EXTERNAL_STATUS.PENDING_OTHERS_2]: "Pending - Others",
  [APPLICATION_EXTERNAL_STATUS.PENDING_PERSONAL_APPEARANCE_INTERVIEW]: "Pending - Personal Appearance for Interview",
  [APPLICATION_EXTERNAL_STATUS.PENDING_UNDER_PROCESS]: "Pending - Under Process",
  [APPLICATION_EXTERNAL_STATUS.DOCS_RECEIVED]: "Docs Received",
  [APPLICATION_EXTERNAL_STATUS.PASSPORT_DISPATCHED_APPROVAL_AWAITED]: "Passport Dispatched / Approval Awaited",
  [APPLICATION_EXTERNAL_STATUS.MRV_OBTAINED]: "MRV Obtained",
  [APPLICATION_EXTERNAL_STATUS.MRV_OBTAINED_APPOINTMENT_TAKEN]: "MRV Obtained / Appointment Taken",
  
  [APPLICATION_EXTERNAL_STATUS.VISA_REJECTED]: "Visa Rejected",
  [APPLICATION_EXTERNAL_STATUS.VISA_OBTAINED]: "Visa Obtained",
  [APPLICATION_EXTERNAL_STATUS.OBTAINED]: "Obtained",
  [APPLICATION_EXTERNAL_STATUS.COLLECTED]: "Collected",
  [APPLICATION_EXTERNAL_STATUS.VISA_GRANTED_SENT]: "Visa Granted / Sent",
  [APPLICATION_EXTERNAL_STATUS.VISA_REJECTED_SENT]: "Visa Rejected / Sent",
  [APPLICATION_EXTERNAL_STATUS.SENT]: "Sent",
  [APPLICATION_EXTERNAL_STATUS.SENT_BACK_WITHOUT_VISA]: "Sent Back Without Visa",
  [APPLICATION_EXTERNAL_STATUS.WITHDRAWN_SENT]: "Withdrawn / Sent",
};

